import type { ScheduleAssessmentResult } from '@/types/views';
import { INSTITUTION } from '@/config/institution';
import { Card, InfoNote, Table, TableWrap, Td, Th } from '@/components/ui';
import { WeeklyCalendar } from '@/components/WeeklyCalendar';
import korphilLogo from '@/assets/korphil-logo.png';

/**
 * One printable General Schedule and Assessment sheet. Shared by the
 * single-student view and the by-section batch view — a batch is just this
 * component repeated once per student, separated by a page break.
 */
export function GsaSnapshotSheet({
  data,
  pageBreakBefore = false,
}: {
  data: ScheduleAssessmentResult;
  pageBreakBefore?: boolean;
}) {
  return (
    <Card className={'print-sheet p-5' + (pageBreakBefore ? ' page-break' : '')}>
      <header className="border-b border-line pb-3 text-center">
        <img src={korphilLogo} alt="" aria-hidden className="mx-auto mb-2 h-16 w-16 object-contain" />
        <p className="text-xs font-semibold uppercase tracking-wide text-ink-700">
          {INSTITUTION.agency}
        </p>
        <p className="text-sm font-semibold text-ink-900">{INSTITUTION.centre}</p>
        <p className="mt-1 text-xs text-ink-500">{INSTITUTION.address}</p>
        <p className="mt-2 text-sm font-semibold uppercase text-ink-900">
          General Schedule and Assessment
        </p>
      </header>

      <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm">
        <Row label="Name" value={data.student.fullName} />
        <Row label="Student ID" value={data.student.studentNumber} />
        <Row label="Program" value={`${data.student.programCode} — ${data.student.programName}`} />
        <Row label="Currently enrolled" value={data.term?.label ?? 'No open term'} />
      </dl>

      {!data.term ? (
        <div className="mt-4">
          <InfoNote tone="warning">
            There is no active term right now, so no schedule or course load can be shown.
          </InfoNote>
        </div>
      ) : data.subjects.length === 0 ? (
        <div className="mt-4">
          <InfoNote tone="warning">
            This student has no enrollment on record for the current term.
          </InfoNote>
        </div>
      ) : (
        <>
          <div className="mt-4">
            <p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-ink-700">
              Course load
            </p>
            <TableWrap>
              <Table className="min-w-[34rem]">
                <thead>
                  <tr>
                    <Th>Course code</Th>
                    <Th>Course name</Th>
                    <Th className="text-right">Units</Th>
                  </tr>
                </thead>
                <tbody>
                  {data.subjects.map((row) => (
                    <tr key={row.id}>
                      <Td className="font-medium text-ink-900">{row.subjectCode}</Td>
                      <Td>{row.subjectTitle}</Td>
                      <Td className="text-right tabular-nums">{row.units}</Td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr>
                    <Td className="font-semibold text-ink-900">Total</Td>
                    <Td> </Td>
                    <Td className="text-right font-semibold tabular-nums text-ink-900">
                      {data.totalUnits}
                    </Td>
                  </tr>
                </tfoot>
              </Table>
            </TableWrap>
          </div>

          <div className="mt-4">
            <p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-ink-700">
              Weekly schedule
            </p>
            <WeeklyCalendar
              schedules={data.schedules}
              emptyHint="No class has been attached to this student's enrolled subjects yet."
            />
          </div>
        </>
      )}

      <p className="mt-6 text-[11px] text-ink-400">
        Generated by {INSTITUTION.systemName} · not valid without the dry seal of the centre.
      </p>
    </Card>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-2">
      <dt className="text-ink-500">{label}:</dt>
      <dd className="font-medium text-ink-900">{value || '—'}</dd>
    </div>
  );
}
